---
name: Class-AlzaboWrapper
version: 0.14
author:
  - 'Dave Rolsky, <autarch@urth.org>'
abstract: Higher level wrapper around Alzabo Row and Table objects
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Alzabo: 0
  Exception::Class: 0
  Params::Validate: 0
  Test::More: 0
build_requires:
  Module::Build: 0
provides:
  Class::AlzaboWrapper:
    file: lib/Class/AlzaboWrapper.pm
    version: 0.14
  Class::AlzaboWrapper::Cursor:
    file: lib/Class/AlzaboWrapper/Cursor.pm
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
