--- #YAML:1.0
name: Class-AlzaboWrapper
version: 0.04
author:
  - Dave Rolsky, <autarch@urth.org>
abstract: |-
  Higher level wrapper around Alzabo Row and Table objects
license: perl
requires:
  Alzabo: 0
  Exception::Class: 0
  Params::Validate: 0
provides:
  Class::AlzaboWrapper:
    file: lib/Class/AlzaboWrapper.pm
    version: 0.04
  Class::AlzaboWrapper::Cursor:
    file: lib/Class/AlzaboWrapper/Cursor.pm
generated_by: Module::Build version 0.23
